name: 🧠 Update Profile Projects

# on:
#   schedule:
#     - cron: "0 */6 * * *"
#   workflow_dispatch:

jobs:
  update-projects:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⚙️ Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: 📦 Install dependencies
        run: pip install requests PyGithub

      - name: 🤖 Run project updater
        run: python .github/scripts/update_projects.py

      - name: 🚀 Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "📦 Updated project list in README"
